name: validate-title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title contains "feature"
        run: |
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          if [[ "${{ github.event.pull_request.title }}" =~ [Ff]eature ]]; then
            echo "✅ Title contains 'feature'."
          else
            echo "❌ Title must contain the word 'feature'."
            exit 1
          fi
